apiVersion: v1
kind: Secret
metadata:
  namespace: jnp2
  name: mysql-projects
  labels:
    app: jnp2
    tier: backend
    component: mysql-projects
type: Opaque
data:
  password: Rjg3MDlBNjQ0NzI1MDYwREYzNTc0OEI1QUU0OUVFQkE=
  root-password: NEJGQjZFNjRBOUQ3QjU0OTNBOEM5QkU5MTMwNDNGREQ=
