apiVersion: v1
kind: Service
metadata:
  namespace: jnp2
  name: proxy
spec:
  selector:
    app: jnp2
    component: proxy
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: http
  type: ClusterIP
