---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jnp2
  name: rabbitmq-pvc
  labels:
    app: jnp2
    component: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi