---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: jnp2
  labels:
    app: jnp2
    component: rabbitmq
spec:
  replicas: 1
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: jnp2
      component: rabbitmq
  template:
    metadata:
      labels:
        app: jnp2
        component: rabbitmq
    spec:
      containers:
        - image: rabbitmq:3.8.8
          imagePullPolicy: IfNotPresent
          name: rabbitmq
          ports:
            - containerPort: 5672
              name: task-queue
          livenessProbe:
            exec:
              command: ["rabbitmqctl", "status"]
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["rabbitmqctl", "status"]
            initialDelaySeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq/mnesia
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
