---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects
  namespace: jnp2
  labels:
    app: jnp2
spec:
  selector:
    matchLabels:
      app: jnp2
      tier: backend
      component: projects
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jnp2
        tier: backend
        component: projects
    spec:
      initContainers:
        - image: rzetelskik/jnp2-projects:latest
          name: init-db
          command: ['/bin/bash', '-c', 'bundle exec rake db:create && bundle exec rake db:migrate']
          envFrom:
            - configMapRef:
                name: mysql-projects-config
          env:
            - name: DB_PASSWORD_PROJECTS
              valueFrom:
                secretKeyRef:
                  name: mysql-projects
                  key: root-password
      containers:
        - image: rzetelskik/jnp2-projects:latest
          name: projects
          envFrom:
            - configMapRef:
                name: mysql-projects-config
          env:
            - name: DB_PASSWORD_PROJECTS
              valueFrom:
                secretKeyRef:
                  name: mysql-projects
                  key: root-password
          ports:
            - containerPort: 80
              name: http
