---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: jnp2
  labels:
    app: jnp2
    component: rabbitmq
spec:
  type: ClusterIP
  ports:
    - name: task-queue
      port: 5672
      targetPort: task-queue
    - name: monitor
      port: 15672
      targetPort: monitor
  selector:
    app: jnp2
    component: rabbitmq