apiVersion: v1
kind: Service
metadata:
  namespace: jnp2
  name: frontend
spec:
  selector:
    app: jnp2
    component: frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: http
  type: LoadBalancer
