apiVersion: v1
kind: Service
metadata:
  namespace: jnp2
  name: mysql-projects
  labels:
    app: jnp2
    tier: backend
    component: mysql-projects
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    app: jnp2
    tier: backend
    component: mysql-projects