apiVersion: v1
kind: Service
metadata:
  name: mysql-accounts
  namespace: jnp2
  labels:
    app: jnp2
    tier: backend
    component: mysql-accounts
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    app: jnp2
    tier: backend
    component: mysql-accounts