---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-projects-myconf
  namespace: jnp2
  labels:
    app: jnp2
    tier: backend
    component: mariadb-projects
data:
  my.cnf: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    innodb_file_per_table=1
    innodb_buffer_pool_size=2G
    innodb_buffer_pool_instances=16
    innodb_read_io_threads=16
    innodb_write_io_threads=16
    innodb_lock_wait_timeout=20
    innodb_log_buffer_size=256M
    innodb_log_file_size=1G
    innodb_flush_log_at_trx_commit=0
    innodb_log_compressed_pages=off
    innodb_checksum_algorithm=crc32
    log-basename=master1
    max_connections=150
    expire_logs_days=1
    plugin_load_add=query_response_time
    query_response_time_stats=ON

    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8

    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-projects-config
  namespace: jnp2
data:
  DB_NAME_PROJECTS: 'projects'
  DB_USER_PROJECTS: 'root'
  DB_HOST_PROJECTS: 'mariadb-projects.jnp2.svc.cluster.local'
